services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextapp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000 
      - NEXT_PUBLIC_API_URL=http://mejoresescuelasmexico.infinitecmexico.com/api
    ports:
      - "3015:3000" 
